// Code generated by lib-go/goflow DO NOT EDIT.

// +build !codeanalysis

package main

import (
	"context"
	"fmt"
)

func assert(b bool) {
	if !b {
		panic("assertion failed")
	}
}

func main() {
	var g Ctx

	g = NewCtx()
	g.Run(context.Background())
	fmt.Println("Test done.")

	fmt.Println("All tests done.")
}
