// Code generated by goflow DO NOT EDIT.

//go:build !codeanalysis

package main

import (
	"context"
	"fmt"

	"github.com/alkemics/goflow/wrappers/mockingjay"
)

func assert(b bool) {
	if !b {
		panic("assertion failed")
	}
}

func main() {
	var g Mockingjay

	g = NewMockingjay()

	ctx := mockingjay.WithMock(context.Background(), "add", 1)
	sum := g.Run(ctx, 10, 20)
	if sum != 1 {
		panic(fmt.Sprintf("expected 1 got %v\n", sum))
	}

	fmt.Println("Test done.")

	fmt.Println("All tests done.")
}
