// Code generated by lib-go/goflow DO NOT EDIT.

//go:build !codeanalysis
// +build !codeanalysis

package main

import (
	"fmt"
)

func assert(b bool) {
	if !b {
		panic("assertion failed")
	}
}

func main() {
	var g Ouputs

	g = NewOuputs()

	ri, ris := g.Run()
	if ri < 0 || ri > 100 {
		panic("invalid ri")
	}
	if len(ris) != 2 {
		panic("ris should have length 2")
	}

	fmt.Println("Test done.")

	fmt.Println("All tests done.")
}
